[tool.poetry]
name = "field_translator"
version = "0.1.0"
description = ""
authors = ["otavio <otavio-dantas@live.com>"]

[tool.poetry.dependencies]
python = "^3.9"
aiokafka = "^0.7.1"
pydantic = "^1.8.2"
aiohttp = "^3.7.4"
python-dateutil = "^2.8.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
mypy = "^0.910"
pylint = "^2.9.3"
autopep8 = "^1.5.7"
python-dotenv = "^0.18.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
