[tool.poetry]
name = "field_translator"
version = "0.1.0"
description = ""
authors = ["otavio <otavio-dantas@live.com>"]

[tool.poetry.dependencies]
python = "^3.9"
aiokafka = "^0.7.1"
pydantic = "^1.8.2"
python-dateutil = "^2.8.1"
uvloop = "^0.16.0"
ujson = "^4.1.0"
msgpack = "^1.0.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-cov = "^2.12.1"
mypy = "^0.910"
pylint = "^2.10.2"
autopep8 = "^1.5.7"
python-dotenv = "^0.19.0"
devtools = "^0.6.1"
lxml = "^4.6.3"
snakeviz = "^2.1.0"
types-ujson = "^0.1.1"
Faker = "^8.12.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
