
@startuml
'https://plantuml.com/class-diagram
class TransformerConfig <<pydantic>> {
}
class TransformerChainConfig <<pydantic>> {
__root__: Sequence[TransformerConfig]
}
abstract Transformer {
    - config: TransformerConfig
    + transform()
}

class TransformerChain {
    - config: TransformerChainConfig
    + transform()
}

class MapKeys {
    - config: MapKeysConfig
    + transform()
}

class MapKeysConfig <<pydantic>> {
    + mapping: dict
}

class AnotherTransform {
    - config: AnotherTransformConfig
    + transform()
}
class AnotherTransformConfig  <<pydantic>> {
}


Transformer *-l- TransformerConfig


TransformerChain -u-|> Transformer
TransformerChain *-d- TransformerChainConfig
'TransformerChainConfig -d-|> TransformerConfig

MapKeys -u-|> Transformer
MapKeys *-d- MapKeysConfig
'MapKeysConfig -d-|> TransformerConfig

AnotherTransform -u-|> Transformer
AnotherTransform *-d- AnotherTransformConfig
'AnotherTransformConfig -d-|> TransformerConfig
@enduml
