@startuml
'https://plantuml.com/class-diagram
class BaseTransformerConfig <<pydantic>> {
}
class TransformerChainConfig <<pydantic>> {
__root__: Sequence[TransformerConfig]
}
class TransformerConfig <<pydantic>> {
command_name: str
}

abstract Transformer {
    config: BaseTransformerConfig
    + transform()
}

class TransformerChain {
    config: TransformerChainConfig
    + transform()
}

class MapKeys {
    - config: MapKeysConfig
    + transform()
}

class MapKeysConfig <<pydantic>> {
    command_name: Literal['map_keys']
    mapping: dict
}



class AnotherTransform {
    - config: AnotherTransformConfig
    + transform()
}



TransformerChain -r-|> Transformer
TransformerChain *-l- TransformerChainConfig

TransformerConfig -u-|> BaseTransformerConfig
TransformerChainConfig --|> BaseTransformerConfig
Transformer --* BaseTransformerConfig

MapKeys -u-|> Transformer
MapKeys *-d- MapKeysConfig
MapKeysConfig -d-|> TransformerConfig
AnotherTransform -u-|> Transformer
AnotherTransform *-d- AnotherTransformConfig
AnotherTransformConfig -d-|> TransformerConfig
@enduml
